### ISSUE TITLE
Is it possible to script an import via the command line?

### ISSUE THREAD

**Issue by j-greig** [Pennebaker/craft-architect#15]

**Comment by Emkaytoo** [comment]
I touched upon this lightly in Issue #9, where I added the request to have a build order config that imports models sequentially. Is this what you're looking for?

I also mentioned a command line interface for creating models that would themselves update the build order.

**Comment by j-greig** [comment]
Yup that's pretty much what I was thinking too, thanks for flagging  👍

**Comment by Emkaytoo** [comment]
Absolutely. If you think of any use cases, add them to #9 so we can make sure to think everything through.
