### ISSUE TITLE
Where to put json files

### ISSUE THREAD

**Issue by jeremyfrank** [Pennebaker/craft-architect#17]
The previous Craft 2 version of The Architect allowed json configuration files to be placed in config/thearchitect, and they would show up under the "Available Files" tab. Will something like this be added to this Craft 3 version of the plugin?

**Comment by Emkaytoo** [comment]
Short answer: yes.

Longer answer: We intended to add something like this, but to further extend it with a way to script out a build order, as mentioned in #9. It'll probably be in the main `/config` directory, similar to how Redactor is now.
