### ISSUE TITLE
Json schema

### ISSUE THREAD

**Issue by H-i-red** [Pennebaker/craft-architect#2]
Hi,

Do you have any examples of json schema for importing fields, sections... ?
The Wiki seems broken, or not updated?

Best regards /

Fredrik

**Comment by H-i-red** [comment]
Found the test.json file, works fine, for testing imports.
(craft/vendor/pennebaker/craft-architect/src/templates/test.json)

**Comment by Emkaytoo** [comment]
Sorry about that @H-i-red. The Wiki was copied from the Craft 2 version and is still being updated in between projects.

There are a few notable differences, and I'm hoping to get to them in the next few days. In the mean time, modeling things after the `test.json` file would be your best bet.

**Comment by Emkaytoo** [comment]
Closing this issue as I've created a new issue encompassing all of the wiki #4
