### ISSUE TITLE
EntryTypes won't import unless Section imports on same model

### ISSUE THREAD

**Issue by Emkaytoo** [Pennebaker/craft-architect#22]
I added a section in a model and then added the fields and entryTypes in a subsequent model (to use in a field). The entryTypes failed to import.

**Comment by spAnser** [comment]
This was not really a bug it was never intended to work like this in the previous Craft 2 version. I consider this updating the Section which would be something that will be implemented later on when doing the command line / build features. The reason being that Architect wants to make sure the section imports properly first before trying to create Entry Types for it. Architect is also programmed to delete the default entry type if it is not used which is only possible if it is imported at the same time as the section.
