### ISSUE TITLE
CP Export: TypeError

### ISSUE THREAD

**Issue by ostark** [Pennebaker/craft-architect#30]
I get this error when I hit the export button in the CP:

```
Argument 1 passed to craft\services\Fields::getLayoutById() must be of the type integer, null given, called in [...]/vendor/twig/twig/lib/Twig/Extension/Core.php on line 1605
```

Bonus:
`php craft architect/export` feels a bit unfished.

**Comment by ostark** [comment]
@spAnser or is it just me?

**Comment by spAnser** [comment]
I think I accidentally might've committed the base setup for implementing the CLI commands but they are not released.

**Comment by spAnser** [comment]
Closed since the feature is not yet implemented and the feature is being tracked in Issue #6
