### ISSUE TITLE
Neo support?

### ISSUE THREAD

**Issue by christianruhstaller** [Pennebaker/craft-architect#32]
I just wanted to know how it looks for the neo support?
Is this feature planned in the near future (or already in development?) or 
do we need still wait some time?

Thanks for the feedback!

**Comment by Emkaytoo** [comment]
This is on the roadmap, but we haven't yet gotten our hands on Neo to try it out. We were fans of Neo for Craft 2 and supported it there, so we'll be doing that for Craft 3 as well.

**Comment by spAnser** [comment]
I will probably work on this some this week. This will probably be version 2.2.11

2.3 features are the main thing on the back burner at the moment.

**Comment by spAnser** [comment]
Let me know how it works out.

**Comment by christianruhstaller** [comment]
First tests seems to work out nice.
