### ISSUE TITLE
Architect shouldn’t be strict about tag group & volume field layouts

### ISSUE THREAD

**Issue by brandonkelly** [Pennebaker/craft-architect#35]
Currently Architect ensures that tag groups and volumes has no more than 1 field layout tab, and that the tab’s name is “Content”.

https://github.com/Pennebaker/craft-architect/blob/964f22f7b760961c8ffad9fde3d8562b9d2a6be4/src/base/VolumeProcessor.php#L36-L44

However those tab names could change if they have been translated into something else. And theoretically Craft may allow users to create custom field layouts for tag groups and volumes in the future. So Architect should just import those field layouts just like any other, and not worry about how many tabs it has or what the tab names are.

**Comment by spAnser** [comment]
Ah sounds good. I think I ran into issues when importing something different so I was attempting to not let a user break the site. I guess that is what backups are for.
