### ISSUE TITLE
Craft 3.1 compatiblity issues?

### ISSUE THREAD

**Issue by christianruhstaller** [Pennebaker/craft-architect#36]
It seems that there are some compatibility issues with the new Craft version.
1. Assets field export fails with an php notice: Trying to get property 'volumeId' of non-object
It seems a id/uid issue
2. Export an entries field and import it to another site and it will loose the associated entry types.

For now these are the only problems I've found.

**Comment by spAnser** [comment]
Looks like craft is storing the attached id using their new ID method.

`volume:23b079b0-ab36-4728-aeac-6113f5904a8a`

By asking for FolderById obviously doesn't work with this ID. Will need to find the alternative method for getting the right volumes. This might affect quite a few things actually.

**Comment by spAnser** [comment]
Looks like this is all documented here: https://craftcms.com/guides/updating-plugins-for-craft-3-1

I may end up rewriting how mapping these types of fields is handled. Which will need some fallback support as well.

I know what and how to fix this it will take some time I don't want to just slap some flex tape on the bug and call it a day.
