### ISSUE TITLE
PHP conflict with default Craft installs

### ISSUE THREAD

**Issue by brandonkelly** [Pennebaker/craft-architect#38]
Since v2.2.12, The Architect has required `symfony/yaml` at `^4.1` (d7f68713eeee4959994548fb35941d74ca72123f).

However `symfony/yaml` 4.1+ [requires](https://github.com/symfony/yaml/blob/80e4bfa9685fc4a09acc4a857ec16974a9cd944e/composer.json#L19) PHP 7.1.3 or later, which conflicts with the default `php` platform requirement that Craft projects have:

https://github.com/craftcms/craft/blob/master/composer.json#L33

You should probably tweak the plugin to require a lower version of `symfony/yaml` that is compatible with PHP 7.0. (For example, Craft 3.1+ requires `symfony/yaml` at `^3.2|^4.0`.) Otherwise people get Composer errors when attempting to install the plugin.

**Comment by spAnser** [comment]
I was personally having errors installing the plugin when I didn't have it set this way while on craft 3.1
