### ISSUE TITLE
Invalid argument supplied for foreach() When importing Routes

### ISSUE THREAD

**Issue by rgbjay** [Pennebaker/craft-architect#39]
When I am importing four custom routes, it is failing and throwing the above exception. JSON is valid and being generated from Architect on another Craft 3 install.

Generated JSON below (I have tried it with both escaped and non-escaped characters FYI):

```
{
  "routes": [
    {
      "template": "_sitemap.html",
      "uriParts": [
        "\/sitemap"
      ]
    },
    {
      "template": "events\/_event-filter",
      "uriParts": [
        "\/fetch-events"
      ]
    },
    {
      "template": "search-results.html",
      "uriParts": [
        "\/search-results"
      ]
    },
    {
      "template": "blog\/_post-filter",
      "uriParts": [
        "\/fetch-posts"
      ]
    }
  ]
}
```
Craft v3.1.25
PHP 7.2.9
MySQL 5.7.23

Any help would be appreciated!

**Comment by spAnser** [comment]
I was able to import this in my test environment.

Also I think the exception didn't get attached.

**Comment by rgbjay** [comment]
Hmm, insteresting.

Sorry the exception that I refer to is the one in the title `Invalid argument supplied for foreach()`

**Comment by spAnser** [comment]
Finally got around to looking at issues again and I found the fix for this. It happened when you had no routes at all on the site. Should be fixed in the next release coming today.
