### ISSUE TITLE
getSiteById() Error when trying to export anything 

### ISSUE THREAD

**Issue by jamielaughton** [Pennebaker/craft-architect#48]
Hi, I'm receiving error:

Argument 1 passed to craft\services\Sites::getSiteById() must be of the type integer, string given, called in /Users/useradmin/Documents/repos/spacecentre/vendor/pennebaker/craft-architect/src/base/Processor.php on line 297

When i try to export anything from architect. The getSiteById function is used throughout the rest of the cms without issue so I'm at a bit of a loss as to why this error is being thrown

Any help would be greatly appreciated

Cheers,
Jame

**Comment by mdominguez** [comment]
Same here, plugin is unusable at this point..

**Comment by spAnser** [comment]
Looks like I missed the notification of this problem. I plan on getting back into a schedule where I can start doing bug fixes and features for this starting today.

**Comment by spAnser** [comment]
Let me know if this works. I have this issue as well but couldn't find the site I was having the issue on.

**Comment by jamielaughton** [comment]
Works perfectly now, thanks for the super quick fix
