### ISSUE TITLE
Error while exporting sections

### ISSUE THREAD

**Issue by cursoruk** [Pennebaker/craft-architect#54]
While attempting to export a section on our Craft 3 site we're experiencing the following error:

![Screenshot 2020-08-13 at 08 31 46](https://user-images.githubusercontent.com/1247059/90160732-11ad0b00-dd8a-11ea-9952-6cf6ca05c6fc.png)

`2020-08-13 00:31:37 [-][1][f21079vvstedadhjdj865mhpmg][error][yii\base\UnknownPropertyException] yii\base\UnknownPropertyException: Getting unknown property: craft\models\EntryType::titleLabel in /Users/john/Sites/test-site.com/vendor/yiisoft/yii2/base/Component.php:154
Stack trace:
#0 /Users/john/Sites/test-site.com/vendor/pennebaker/craft-architect/src/base/EntryTypeProcessor.php(106): yii\base\Component->__get('titleLabel')
#1 /Users/john/Sites/test-site.com/vendor/pennebaker/craft-architect/src/base/SectionProcessor.php(124): pennebaker\architect\base\EntryTypeProcessor->export(Object(craft\models\EntryType))
#2 /Users/john/Sites/test-site.com/vendor/pennebaker/craft-architect/src/base/SectionProcessor.php(141): pennebaker\architect\base\SectionProcessor->export(Object(craft\models\Section))
#3 /Users/john/Sites/test-site.com/vendor/pennebaker/craft-architect/src/controllers/DefaultController.php(140): pennebaker\architect\base\SectionProcessor->exportById('2')
#4 [internal function]: pennebaker\architect\controllers\DefaultController->actionExport()
#5 /Users/john/Sites/test-site.com/vendor/yiisoft/yii2/base/InlineAction.php(57): call_user_func_array(Array, Array)
#6 /Users/john/Sites/test-site.com/vendor/yiisoft/yii2/base/Controller.php(180): yii\base\InlineAction->runWithParams(Array)
#7 /Users/john/Sites/test-site.com/vendor/craftcms/cms/src/web/Controller.php(181): yii\base\Controller->runAction('export', Array)
#8 /Users/john/Sites/test-site.com/vendor/yiisoft/yii2/base/Module.php(528): craft\web\Controller->runAction('export', Array)
#9 /Users/john/Sites/test-site.com/vendor/craftcms/cms/src/web/Application.php(294): yii\base\Module->runAction('architect/defau...', Array)
#10 /Users/john/Sites/test-site.com/vendor/yiisoft/yii2/web/Application.php(103): craft\web\Application->runAction('architect/defau...', Array)
#11 /Users/john/Sites/test-site.com/vendor/craftcms/cms/src/web/Application.php(279): yii\web\Application->handleRequest(Object(craft\web\Request))
#12 /Users/john/Sites/test-site.com/vendor/yiisoft/yii2/base/Application.php(386): craft\web\Application->handleRequest(Object(craft\web\Request))
#13 /Users/john/Sites/test-site.com/htdocs/index.php(22): yii\base\Application->run()
#14 {main}`

**Comment by rbaud** [comment]
Looks like this is related to the field changes in the Craft 3.5 update. Related issue here: https://github.com/Pennebaker/craft-architect/issues/53

**Comment by casvangrunsven** [comment]
Hello, I have exactly the same issue. Do you have any idea when this will be resolved or a workaround?
Thanks in advance!
