### ISSUE TITLE
Updating matrix field does not add or update fields

### ISSUE THREAD

**Issue by brandondeweese** [Pennebaker/craft-architect#55]
Attached screenshot. Trying to import/update matrix on left with matrix content on right. Fields not updating...?
![Screen Shot 2020-10-22 at 11 00 42 AM](https://user-images.githubusercontent.com/18017918/96911691-09421200-1456-11eb-8a37-1bb2bdc8ac0a.png)

**Comment by tsawitzki** [comment]
+1, same issue here!
