### ISSUE TITLE
Explanation of the Blueprint feature

### ISSUE THREAD

**Issue by tsawitzki** [Pennebaker/craft-architect#56]
Great plugin, great idea! 
I just don't get the idea of how the Blueprints work from the documentation which is not really complete yet. Please clarify what the Blueprint does and how to use it.

**Comment by spAnser** [comment]
Exported JSON data can be saved into the config/architect folder if memory serves and can be quickly loaded in with a single click.

**Comment by tsawitzki** [comment]
Okay, thanks for clarifying! Really looking forward to an update and a full documentation.
