### ISSUE TITLE
Conflict of symfony/yaml version on Craft 3.6

### ISSUE THREAD

**Issue by rogerdawkins** [Pennebaker/craft-architect#57]
Just trying to update my Craft version to 3.6.0.1 but I get a conflict error. It appears that 3.6.0.1 requires symfony/yaml ^5.2.1 but Architect requires symfony/yaml ^3.2|^4.0.

**Comment by proimage** [comment]
I "solved" this by **uninstalling** Architect—it's not necessary for the day-to-day functionality. Note that merely "disabling" or even "removing" it is not sufficient, as the conflict is at the composer level, which is deeper than those two options (which are at the Craft level).

**Comment by rogerdawkins** [comment]
> I "solved" this by **uninstalling** Architect—it's not necessary for the day-to-day functionality. Note that merely "disabling" or even "removing" it is not sufficient, as the conflict is at the composer level, which is deeper than those two options (which are at the Craft level).

Thanks. I don't use it on production systems but it is useful on development. I was highlighting the issue so that the developer was aware of the issue.

**Comment by spAnser** [comment]
I tried to support json and yaml but idk if anyone actually even uses the yaml part.

I'm curious if I could remove yaml support without causing trouble.

**Comment by spAnser** [comment]
Either way this should be fixed now and functional as long as Yaml:parse hasn't changed in the 5.x version.
