### ISSUE TITLE
Craft latest version, cannot see export page

### ISSUE THREAD

**Issue by vitalijalbu** [Pennebaker/craft-architect#65]
**Describe the bug**
Cannot see export page

**To Reproduce**
1. install plugin
2. go to export page

**Screenshots**
![Screenshot 2023-06-23 alle 08 07 36](https://github.com/Pennebaker/craft-architect/assets/40239902/1d904baf-31ce-4f15-a858-c18b88b6872f)

**Comment by vitalijalbu** [comment]
@spAnser any updates fro this bug??

**Comment by spAnser** [comment]
Oh I've been bad and didn't see this. I'll have a fix soon

**Comment by spAnser** [comment]
I couldn't replicate the bug. But it should be fixed. I check if the site is null before getting the handle now.
It seems as if it has a site setting for maybe a delete site still in the db for one of your sections?

**Comment by spAnser** [comment]
Released as 4.0.1
