### ISSUE TITLE
Add build order configurator

### ISSUE THREAD

**Issue by Emkaytoo** [Pennebaker/craft-architect#9]
Sometimes I model the CMS in iterations, where one model is dependent on a previous one. Kind of like a Rails/Django migration. 

It would be cool to have some sort of build order configuration so that models could be built in sequential order as new functionality or content are added. 

It would also be cool if there was a command line (#6) command like `architect make model {modelName}` that would add [the basic model scaffolding](https://github.com/Pennebaker/craft-architect/wiki/Initializing-a-Model) and update the build order.

**Comment by j-greig** [comment]
+1 for this
